version: '3.8'

services:
  tests:
    build: .
    env_file:
      - .env
    volumes:
      - ./allure-results:/app/allure-results
    networks:
      - test-network

  allure:
    image: frankescobar/allure-docker-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    networks:
      - test-network

networks:
  test-network:
