[pytest]
# Все опции запуска собираем в одну строку addopts
addopts = --headed --browser chromium --alluredir=allure-results --clean-alluredir

# Базовый URL оставляем отдельной строкой
base_url = https://my.business-pad.com